[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "oobmap"
version = "0.1.0"
description = "CTF-first out-of-band blind injection extractor powered by interactsh logs"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [
  { name = "Charlot DEDJINOU" }
]
keywords = [
  "ctf",
  "security",
  "sqli",
  "blind-sqli",
  "oob",
  "oast",
  "interactsh",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Security",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Charlot-DEDJINOU/oobmap"
Repository = "https://github.com/Charlot-DEDJINOU/oobmap"
Issues = "https://github.com/Charlot-DEDJINOU/oobmap/issues"

[project.scripts]
oobmap = "oobmap.cli:main"

[tool.setuptools.packages.find]
include = ["oobmap*"]
